name: Build Flet APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Zaktualizowane do v4

      - name: Setup Java 17
        uses: actions/setup-java@v4 # Zaktualizowane do v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5 # Zaktualizowane do v5
        with:
          python-version: '3.10'

      - name: Install Flet and Requests
        run: pip install flet requests

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build APK
        run: flet build apk --module-name czat_mobile --pip-install requests --include-internet-permission

      - name: Upload APK
        uses: actions/upload-artifact@v4 # TO JEST TA KLUCZOWA ZMIANA (v4)
        with:
          name: MojCzat-Mobile-APK
          path: build/apk/*.apk
