name: Build Flet APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files (Debug)
        run: ls -R  # Sprawdzimy, czy plik .py na pewno tam jest

      - name: Setup Java (Potrzebne do Androida)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Flet
        run: pip install flet

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build APK
        run: flet build apk czat_mobile.py

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MojCzat-Mobile
          path: build/apk/*.apk
